### ISSUE TITLE
Owner is trying to take it back 

### ISSUE THREAD

**Issue by Jack5079** [mollersuite/etcetera.dev#1]
![Screenshot_20231220_193238_K-9 Mail.png](https://github.com/mollersuite/etcetera.dev/assets/29169102/90e66227-31bb-42ff-9ee4-3c4cf0b01c85)

I don't have a clue what to do but I need to fix this before the Method apps launch

**Comment by Jack5079** [comment]
Don't think this is something I can fix so just have the reaction
![Screenshot_20231220_194517](https://github.com/mollersuite/etcetera.dev/assets/29169102/a02e4d1d-f186-4be8-93f2-f5e5f2227b90)
To @joetcetera, the appearent owner of Etcetera.dev: Hello, thank you, and sorry.  <img height=16 src=https://fyle.uk/verygood.png>
I should go remove the CNAME from this repo

I think I referenced this domain a lot when I took it over so I'll have to fix that instead

**Comment by Jack5079** [comment]
https://github.com/mollersuite/etcetera.dev/commit/3cf14b7b491fe6ccfc3db56b6ef6b19d02cf46e1 cname has been removed

**Comment by Jack5079** [comment]
I should write a blog post about this, userstyles, and mollermethod they have something in common that we need to avoid

**Comment by joetcetera** [comment]
It's normal, this domain is mine, you stole it from me. No comment ...
You want it, you pay, nothing could be simpler!

**Comment by nbitzz** [comment]
this man should be promoted to CEO of Mollersuite Incorporated.

**Comment by joetcetera** [comment]
Hello,
I was no longer used in the domain but the best would have been to ask me before I seize it ...

**Comment by nbitzz** [comment]
> Hello, I was no longer used in the domain but the best would have been to ask me before I seize it ...

I don't think any of us even knew you existed lmao
Sorry about that <img src="https://mahiro.oyama.pictures/Sorry" height=32 >
